apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bwe9vdqfw-nodejs 
  janus-idp.io/tekton: bwe9vdqfw-nodejs
  backstage.io/kubernetes-id: bwe9vdqfw-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bwe9vdqfw-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  